CREATE DATABASE CHN_PRUEBA;

USE CHN_PRUEBA;

CREATE TABLE CLIENTE(
ID_CLIENTE INTEGER PRIMARY KEY IDENTITY NOT NULL,
CUI			VARCHAR(25) NOT NULL,
NOMBRE		VARCHAR(25) NOT NULL,
APELLIDO	VARCHAR(25) NOT NULL,
DIRECCION	VARCHAR(64) NOT NULL,
TELEFONO	VARCHAR(25) NOT NULL
);


CREATE TABLE TIPO_CUENTA(
ID_TIPO		INTEGER PRIMARY KEY IDENTITY NOT NULL,
TIPO_CUENTA VARCHAR(10) NOT NULL
);

INSERT INTO TIPO_CUENTA VALUES('AHORRO');
INSERT INTO TIPO_CUENTA VALUES('MONETARIA');

SELECT * FROM TIPO_CUENTA;

CREATE TABLE CUENTA(
ID_CUENTA		INTEGER PRIMARY KEY IDENTITY NOT NULL,
NUMERO_CUENTA	VARCHAR(25) NOT NULL,
SALDO			NUMERIC(20,2) NOT NULL,
ID_CLIENTE		INTEGER,
ID_TIPO			INTEGER,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
FOREIGN KEY(ID_TIPO) REFERENCES TIPO_CUENTA(ID_TIPO)
);


SELECT * FROM CUENTA;

CREATE TABLE ENCABEZADO_CHEQUERA(
ID_CHEQUERA		INTEGER PRIMARY KEY IDENTITY NOT NULL,
NUMERO_CHEQUERA VARCHAR(25) NOT NULL,
ID_CLIENTE		INTEGER,
ID_CUENTA		INTEGER,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
FOREIGN KEY(ID_CUENTA) REFERENCES CUENTA(ID_CUENTA)
);


CREATE TABLE CHEQUE(
ID_CHEQUE			INTEGER PRIMARY KEY IDENTITY NOT NULL,
CORRELATIVO_INICIO	VARCHAR(25) NOT NULL,
CORRELATIVO_FIN		VARCHAR(25) NOT NULL,
ID_CHEQUERA			INTEGER,
FOREIGN KEY(ID_CHEQUERA) REFERENCES ENCABEZADO_CHEQUERA(ID_CHEQUERA)
);



